version: "3.9"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
  migrations:
    image: maxgus/birdcord:migrations-latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - CONNECTION_STRING=${CONNECTION_STRING}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
  discord:
    image: maxgus/birdcord:discord-latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_ID=${DISCORD_ID}
      - CONNECTION_STRING=${CONNECTION_STRING}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15

volumes:
  pg-data: