version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: bot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30