services:
  db-dev:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "50051:5432"
    env_file:
      - dev.env
    networks:
      - birdcord-dev
  adminer-dev:
    image: adminer
    restart: unless-stopped
    ports:
      - "50052:8080"
    env_file:
      - dev.env
    networks:
      - birdcord-dev
  redis-dev:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "50053:6379"
      - "50054:8001"
    env_file:
      - dev.env
    networks:
      - birdcord-dev

networks:
  birdcord-dev:
    driver: bridge