services:
  adminer:
    image: adminer
    ports:
      - '8085:8080'
    env_file:
      - .env
    networks:
      - birdcord
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - birdcord
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis-data:/data
    networks:
      - birdcord
  migrations:
    image: maxgus/birdcord:migrations-latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - CONNECTION_STRING=${CONNECTION_STRING}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
    networks:
      - birdcord
  discord:
    image: maxgus/birdcord:discord-latest
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
    networks:
      - birdcord

volumes:
  pg-data:
  redis-data:

networks:
  birdcord:
    driver: bridge