version: "3.9"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file: .env
  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migrations
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
  discord:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: discord
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
