version: "3.9"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
  migrations:
    image: maxgus/birdcord:migrations-latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - CONNECTION_STRING=${CONNECTION_STRING}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
  discord:
    image: maxgus/birdcord:discord-latest
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15

volumes:
  pg-data: