version: '3'

vars:
  PROJECT: github.com/maxguuse/birdcord

tasks:
  generate-sqlc:
    vars:
      CONFIG: ./configs/sqlc.yaml
    cmds:
      - sqlc generate -f {{.CONFIG}}
  generate-grpc:
    vars:
      PROTOS: libs/grpc/proto
      GENERATED: libs/grpc/generated
    cmds:
      - mkdir -p {{.GENERATED}}
      - protoc
        -I {{.PROTOS}}
        --go_out=module={{.PROJECT}}/{{.GENERATED}}:{{.GENERATED}}
        --go-grpc_out=module={{.PROJECT}}/{{.GENERATED}}:{{.GENERATED}}
        {{.PROTOS}}/*.proto

