version: '3'

vars:
  PROJECT: github.com/maxguuse/birdcord

dotenv:
  - "dev.env"

tasks:
  dev-migrate-up:
    desc: "Run migrations for development DB up"
    aliases:
      - migrate-up
    cmds:
      - task: migrate
        vars:
          DIRECTION: up
  dev-migrate-down:
    desc: "Run migrations for development DB down"
    aliases:
      - migrate-down
    cmds:
      - task: migrate
        vars:
          DIRECTION: down
  migrate:
    internal: true
    cmd: goose -dir libs/migrations/migrations postgres {{.CONNECTION_STRING}} {{.DIRECTION}}
  generate:
    desc: "Generate code for SQLC and gRPC"
    aliases:
      - gen
    cmds:
      - task: generate-sqlc
      - task: generate-grpc
  generate-sqlc:
    desc: "Generate code for SQLC"
    aliases:
      - gen-sqlc
      - sqlc
    vars:
      CONFIG: ./configs/sqlc.yaml
    cmds:
      - sqlc generate -f {{.CONFIG}}
    sources:
      - "libs/sqlc/sql/*.sql"
  generate-grpc:
    desc: "Generate code for gRPC"
    aliases:
      - gen-grpc
      - grpc
    vars:
      PROTOS: libs/grpc/proto
      GENERATED: libs/grpc/generated
    cmds:
      - mkdir -p {{.GENERATED}}
      - protoc
        -I {{.PROTOS}}
        --go_out=module={{.PROJECT}}/{{.GENERATED}}:{{.GENERATED}}
        --go-grpc_out=module={{.PROJECT}}/{{.GENERATED}}:{{.GENERATED}}
        {{.PROTOS}}/*.proto
    sources:
      - "{{.PROTOS}}/*.proto"

