version: '3'

vars:
  PROJECT: github.com/maxguuse/birdcord

dotenv:
  - "dev.env"

tasks:
  dev-migrate-up:
    desc: "Run migrations for development DB up"
    aliases:
      - migrate-up
    cmds:
      - task: migrate
        vars:
          DIRECTION: up
  dev-migrate-down:
    desc: "Run migrations for development DB down"
    aliases:
      - migrate-down
    cmds:
      - task: migrate
        vars:
          DIRECTION: down
  migrate:
    internal: true
    cmd: goose -dir libs/migrations/migrations postgres {{.CONNECTION_STRING}} {{.DIRECTION}}
  generate:
    desc: "Generate code for SQLC and gRPC"
    aliases:
      - gen
    cmds:
      - task: generate-sqlc
      - task: generate-grpc
  generate-jet:
    desc: "Generate code for Jet SQL builder"
    aliases:
      - gen-jet
      - jet
    cmds:
      - jet 
        -dsn={{.CONNECTION_STRING}}
        -ignore-tables=goose_db_version
        -path=./libs/jet/generated
