// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: guilds.sql

package queries

import (
	"context"
)

const createGuilds = `-- name: CreateGuilds :execrows
INSERT INTO guilds ("discord_guild_id") 
VALUES (UNNEST($1::varchar[])) 
ON CONFLICT ("discord_guild_id") DO NOTHING
`

func (q *Queries) CreateGuilds(ctx context.Context, discordGuildIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, createGuilds, discordGuildIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGuildByDiscordID = `-- name: GetGuildByDiscordID :one
SELECT id, discord_guild_id FROM guilds WHERE discord_guild_id = $1
`

func (q *Queries) GetGuildByDiscordID(ctx context.Context, discordGuildID string) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildByDiscordID, discordGuildID)
	var i Guild
	err := row.Scan(&i.ID, &i.DiscordGuildID)
	return i, err
}
