// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: messages.sql

package queries

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    discord_message_id,
    discord_channel_id
) VALUES (
    $1, $2
) RETURNING id, discord_message_id, discord_channel_id
`

type CreateMessageParams struct {
	DiscordMessageID string `json:"discord_message_id"`
	DiscordChannelID string `json:"discord_channel_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.DiscordMessageID, arg.DiscordChannelID)
	var i Message
	err := row.Scan(&i.ID, &i.DiscordMessageID, &i.DiscordChannelID)
	return i, err
}
