// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Poll struct {
	ID              int32       `json:"id"`
	Title           pgtype.Text `json:"title"`
	DiscordToken    pgtype.Text `json:"discord_token"`
	DiscordAuthorID pgtype.Text `json:"discord_author_id"`
	DiscordGuildID  pgtype.Text `json:"discord_guild_id"`
	Active          pgtype.Bool `json:"active"`
}

type PollsOption struct {
	ID     int32       `json:"id"`
	Title  pgtype.Text `json:"title"`
	PollID pgtype.Int4 `json:"poll_id"`
}

type VotedUser struct {
	ID        int32       `json:"id"`
	DiscordID pgtype.Text `json:"discord_id"`
	OptionID  pgtype.Int4 `json:"option_id"`
	PollID    pgtype.Int4 `json:"poll_id"`
}
