// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: polls.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (
    title, 
    author_id, 
    guild_id
) VALUES (
    $1, $2, $3
) RETURNING id, title, created_at, guild_id, author_id
`

type CreatePollParams struct {
	Title    string      `json:"title"`
	AuthorID pgtype.Int4 `json:"author_id"`
	GuildID  int32       `json:"guild_id"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Title, arg.AuthorID, arg.GuildID)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.GuildID,
		&i.AuthorID,
	)
	return i, err
}
