// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: poll_messages.sql

package queries

import (
	"context"
)

const createPollMessage = `-- name: CreatePollMessage :exec
INSERT INTO poll_messages (
    poll_id, 
    message_id
) VALUES (
    $1, $2
)
`

type CreatePollMessageParams struct {
	PollID    int32 `json:"poll_id"`
	MessageID int32 `json:"message_id"`
}

func (q *Queries) CreatePollMessage(ctx context.Context, arg CreatePollMessageParams) error {
	_, err := q.db.Exec(ctx, createPollMessage, arg.PollID, arg.MessageID)
	return err
}
